base_url = "https://creatio.top/"
# base_url = "http://127.0.0.1:1111/"

default_language = "en"
compile_sass = true
title = "Creatio"
description = "My personal blog site."
generate_feed = true
# output_dir = "output"

taxonomies = [
  { name = "tags", paginate_by = 5 },
  { name = "authors", paginate_by = 5 },
]

build_search_index = true

[search] # Options specific to elasticlunr search.
# index format can be: elasticlunr_json or elasticlunr_javascript
# index_format = "elasticlunr_json"
include_title = true       # include title of page/section in index
include_description = true # include description of page/section in index
include_content = true     # include rendered content of page/section in index
# truncate_content_length = 100 # Truncate at nth character. May be useful if index is getting too large.

[markdown]
line_numbers = true
linenos = true
highlight_code = true
# highlight_theme = "css"
# render_emoji = false
external_links_target_blank = true # rel="noopener"
external_links_no_follow = false   # rel="nofollow"
external_links_no_referrer = false # rel="noreferrer"
smart_punctuation = false          # `...` to `…`, `"quote"` to `“curly”` etc

[language.zh]
title = "Creatio"
build_search_index = true

[extra]
banner = ""
date_format = '%Y-%m-%d'

theme = 'mine'
bg = "dark"
inverted = false

themes = "Theme"
schemes = "Color Scheme"
search = 'Search'
tag = 'Posts by Topic'
tags = 'Posts by Topics'

links = [
  { title = 'Articles', url = 'articles' },
  # { title = 'Authors', url = 'authors' },
  { title = 'About', url = 'about' },
  { title = 'Topics', url = 'tags' },
  # { title = 'Github', url = 'https://github.com/aquarv' },
]
email = "yang@creatio.top"
icons = [
  { title = 'Github', icon = 'github', url = 'https://github.com/aquarv' },
  # {title = 'Facebook', icon = 'facebook-f', url = 'https://www.facebook.com'},
  # {title = 'Instagram', icon = 'instagram', url = 'https://www.instagram.com'},
  # {title = 'Twitter', icon = 'twitter', url = 'https://twitter.com'},
  # {title = 'YouTube', icon = 'youtube', url = 'https://www.youtube.com'},
  # {title = 'Bilibili', icon = 'bilibili', url = 'https://www.bilibili.com'},
]

# Do not change this variables
data_themes = [
  'default',
  'mine',
  'cerulean',
  'cosmo',
  'cyborg',
  'darkly',
  'flatly',
  'journal',
  'litera',
  'lumen',
  'lux',
  'materia',
  'minty',
  'morph',
  'pulse',
  'quartz',
  'sandstone',
  'simplex',
  'sketchy',
  'slate',
  'solar',
  'spacelab',
  'superhero',
  'united',
  'vapor',
  'yeti',
  'zephyr',
]
data_schemes = [
  'dark',
  'light',
  'primary',
  'primary inverted',
  'secondary',
  'secondary inverted',
  'success',
  'success inverted',
  'danger',
  'danger inverted',
  'warning',
  'warning inverted',
  'info',
  'info inverted',
]

[extra.beaudar]
enabled = true
repo = "aquarv/aquarv.github.io"
branch = "main"
issue_term = "title"
label = "💬 评论"
theme = "preferred-color-scheme"
# comment-order = "desc"
# input-position = "top"
